<?php
/**
 * Plugin definition.
 */

$plugin = array(
  'title' => t('Four column 25 left stack profile topic fp'),
  'category' => t('Columns: 4'),
  'icon' => 'panels_fourcol_25_left_stack_profile_topic_fp.png',
  'theme' => 'panels_fourcol_25_left_stack_profile_topic_fp',
  /* 'css' => 'panels_fourcol_25_left_stack_profile.css', */
  'admin css' => 'panels_fourcol_25_left_stack_profile_topic_fp.css',
  'regions' => array(
    'top' => t('Top'),
    'left_top_1' => t('Left top 1'),
    'left_top_2' => t('Left top 2'),
    'left_top_3' => t('Left top 3'),
    'left_top_4' => t('Left top 4'),
    'left_top_5' => t('Left top 5'),
    'left_top_6' => t('Left top 6'),
    'left_top_7' => t('Left top 7'),
    'left_top_8' => t('Left top 8'),
    'left_top_9' => t('Left top 9'),
    'left_top_10' => t('Left top 10'),
    'left_top_11' => t('Left top 11'),
    'left_top_12' => t('Left top 12'),
    'left_one' => t('Left one'),
    'left_two' => t('Left two'),
    'right' => t('Right column'),
    'bottom' => t('Bottom'),
  ),
);
