<?php

/**
 * @file
 * Module file for roskilde_royalslider_extra module.
 */

/**
 * Implements hook_libraries_info().
 */
function roskilde_royalslider_extra_libraries_info() {
  $libraries['royalslider'] = array(
    'name' => 'RoyalSlider',
    'vendor url' => 'http://dimsemenov.com/plugins/royal-slider/',
    'download url' => 'http://dimsemenov.com/plugins/royal-slider/pricing/',
    'version arguments' => array(
      'file' => 'jquery.royalslider.min.js',
      'pattern' => '/jquery.royalslider v(\d+\.+\d+\.+\d+)/',
      'lines' => 3,
    ),
    'files' => array(
      'js' => array(
        'jquery.royalslider.min.js',
        'jquery.easing-1.3.js',
      ),
      'css' => array(
        'royalslider.css',
        'skins/minimal-white/rs-minimal-white.css',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_preprocess_field().
 */
function roskilde_royalslider_extra_preprocess_field(&$variables) {
  if ("field_image_data" == $variables['element']['#field_name']) {
    $bundles = array('article', 'webform', 'event', 'editorial_news');
    if (FALSE !== array_search($variables['element']['#bundle'], $bundles)) {
      libraries_load('royalslider');
      drupal_add_js(drupal_get_path('module', 'roskilde_royalslider_extra') . '/js/royalslider.settings.js');
    }
  }
}
