<?php
/**
 * @file
 * banner_element_list_view.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function banner_element_list_view_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-banner_element-field_unit'.
  $field_instances['node-banner_element-field_unit'] = array(
    'bundle' => 'banner_element',
    'default_value' => NULL,
    'default_value_label_token' => 0,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'i18n_taxonomy',
        'settings' => array(
          'conditions' => array(),
        ),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_unit',
    'label' => 'Center',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'apply_chosen' => '',
      ),
      'type' => 'options_select',
      'weight' => 10,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Center');

  return $field_instances;
}
